version: "3.8"

services:
  hotel-db:
    image: postgres:latest
    container_name: hotel-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: hotel
    ports:
      - "5432:5432"
    volumes:
      - hotel-db-data:/var/lib/postgresql/data
    networks:
      - hotel-net

networks:
  hotel-net:
    driver: bridge

volumes:
  hotel-db-data:
