services:
  hotel-db:
    image: postgres:latest
    container_name: hotel-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Apache7300
      POSTGRES_DB: hotel-db
    ports:
      - "5433:5432"  
    volumes:
      - hotel-db-data:/var/lib/postgresql/data 
    networks:
      - hotel-net

networks:
  hotel-net:
    driver: bridge

volumes:
  hotel-db-data:
    driver: local 
